enabled:
  sources:
    - {name: flatfox-zurich,      plugin: source-flatfox,              config: plugins/source-flatfox.yaml}
    - {name: homegate-zurich,     plugin: source-homegate,             config: plugins/source-homegate.yaml}
    - {name: realadvisor-zurich,  plugin: source-realadvisor,          config: plugins/source-realadvisor.yaml}
    - {name: immoscout24-sitemap, plugin: source-immoscout24-sitemap,  config: plugins/source-immoscout24-sitemap.yaml}
    - {name: immobilier-zurich,   plugin: source-immobilier-ch,        config: plugins/source-immobilier-ch.yaml}
  notifiers:
    - {name: telegram, plugin: notifier-telegram, config: plugins/notifier-telegram.yaml}
log:
  level: info
